version: '2'
services:
  db:
    image: postgres:9.3.16
    ports:
      - "5432"
    
  web:
    build: .
    command: bash -c "which rails && printenv && rails server -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/demo_docker